### PR TITLE
paddle clip and fix collisions paddle with area border

### PR DESCRIPTION
**Pull request by gclement42**
I fixed the paddle clipping, which is was caused by paddle position send in a loop
also I fixed the paddle collisions bug, now i check the paddle collision with borders in server side

This branch is merge with "11-restart-after-backmenu" , otherwise i can't test online game

### CODE REVIEW

**Review by maujogue — CHANGES_REQUESTED** [review]
ws://0.0.0.0:8080/ws/lobby/1/
Firefox can’t establish a connection to the server at ws://0.0.0.0:8080/ws/lobby/1/. 

Same issue as before, can't connect to online, maybe the changes on the other branch weren't merged into this one.

**Review by MarcelCerdan — APPROVED** [review]
Good for me but there's a little bug when switching direction with the paddles and the hitbox is a little too small

**Review by boulatrousse — DISMISSED** [review]
Everything seems good to me too. Still a little rollback though but it's better than before

**Review by boulatrousse — APPROVED** [review]
Same

**Pull request merged**
