### PR TITLE
Websockets + nginx conf + router

### PR DESCRIPTION
**Pull request by maujogue**
- WebSockets now **work** ! Turns out Gunicorn does not support websockets...
- Nginx proxy container was merged with the nginx front. The latter now opens the port _8000_ for the front and the backend is accessible through port _8000/api/_
- Backend is now built on https, sharing certificates with the frontend
- Fetch requests are working (register on the sign up button is done)
- The router has been modified to redirect all unknowns urls to the LandingPage

### CODE REVIEW

**Review by boulatrousse — APPROVED** [review]
Everything  seems good to me

**Review by MarcelCerdan — CHANGES_REQUESTED** [review]
There are errors when we try to launch the game : 

GET https://unpkg.com/three@0.159.0/examples/jsm/loaders/FontLoader.js

Loading module from “https://unpkg.com/three@0.159.0/examples/jsm/loaders/FontLoader.js” was blocked because of a disallowed MIME type (“text/html”).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/three@0.159.0/examples/jsm/loaders/FontLoader.js. (Reason: CORS request did not succeed). Status code: (null).

**Comment by maujogue** [comment]
@MarcelCerdan seems like threeJS's CDN was down, I updated it to its latest version (163), can you check again ?

**Review by MarcelCerdan — CHANGES_REQUESTED** [review]
Nice, the error is fixed but the online doesn't work. When clicking 'Quick play' i have this error :

Firefox can’t establish a connection to the server at wss://127.0.0.1:8000/ws/lobby/. online.js:93:17
Connection closed 1015 <empty string>

**Review by gclement42 — APPROVED** [review]

**Review by MarcelCerdan — APPROVED** [review]

**Pull request merged**
